### ISSUE TITLE
no such file to load -- minitest/autorun (LoadError)

### ISSUE THREAD

**Issue by Moximitre** [seattlerb/ruby2ruby#33]
Hi, folks. 

I'm currently attempting to learn Ruby via exercism.io, and the first issue I'm coming across is that the Ruby Gem minitest will not load.  I'm not sure where I Need to put it, or really even how to make sure I have it. I'm running OSX for this work.

I've tried rake install_plugins, which gives the error "No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)"

Thanks

**Comment by zenspider** [comment]
If you're using ruby 1.9 or higher, you should have everything you need as ruby ships with minitest.

Otherwise, a simple `gem install minitest` should suffice.

**Comment by zenspider** [comment]
Also, why is this on ruby2ruby?

**Comment by zenspider** [comment]
No response from OP. I close issues w/ no communication. Please respond.

**Comment by Moximitre** [comment]
My apologies.  I'm new to github, and that forum is one that popped up in a
google search and I just rolled with it.  I'm still having the issue, but
have had to shelve the project for a few weeks.

On Tue, Mar 17, 2015 at 11:17 PM, Ryan Davis <notifications@github.com>
wrote:

> No response from OP. I close issues w/ no communication. Please respond.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seattlerb/ruby2ruby/issues/33#issuecomment-82732831>.
>



-- 
Simon J. Lach
slach1@gmail.com
