### ISSUE TITLE
Upgrade sexp_processor to 4.5.0 & ruby_parser to 3.6.5; bump gem

### ISSUE THREAD

**Issue by saizai** [seattlerb/ruby2ruby#34]
@zenspider sexp_processor & ruby_parser are out of date (4.0, 3.1 vs 4.5.0, 3.6.5), which causes dependency issues.

**Comment by zenspider** [comment]
Based on all the other tickets you filed today, I think you misunderstand what the "~>" dependency specifier does. "~> x.y" means `v > (x+1) && v >= x.y`. So "out of date" is incorrect as my dependencies are declared as:

```ruby
  dependency "sexp_processor", "~> 4.0"
  dependency "ruby_parser",    "~> 3.1"
```

which matches both 4.0.0 and 4.5.0 for sexp_processor and 3.1 and 3.6.5 for ruby_parser.

**Comment by saizai** [comment]
Mea culpa.

**Comment by zenspider** [comment]
Does that make sense tho? Please let me know if I'm misunderstanding the scenario. I know you brought up highline conflicts in a different ticket. If there are any conflicts on my side, I'd like to know.
