### ISSUE TITLE
Seemingly unnecessary parentheses

### ISSUE THREAD

**Issue by jaredbeck** [seattlerb/ruby2ruby#35]
```ruby
hsh = RubyParser.new.parse("{foo: bar}")
# => s(:hash, s(:lit, :foo), s(:call, nil, :bar))
Ruby2Ruby.new.process(hsh)
# => "{ :foo => (bar) }"
```

In this example, the parentheses around `bar` are unnecessary.

- ruby_parser 3.6.5
- ruby2ruby 2.1.3

**Comment by zenspider** [comment]
I'm gonna close this one since you have it handled in your PR. Feel free to open more tickets for specific situations and we can see what we can do to reduce/eliminate.
