### ISSUE TITLE
restrict version dependency on sexp_processor

### ISSUE THREAD

**Issue by boutil** [seattlerb/ruby2ruby#46]
Hi,

With the latest version 2.3, I am seeing test errors like this with sexp_processor 4.4.4:

```
TestRuby2Ruby2#test_block_mystery_block [(eval):8]:
--- expected
+++ actual
@@ -1,4 +1,4 @@
-"a(b) do
+"a(b) do ||
   if b then
     true
   else
```

Updating sexp_processor to 4.7 makes all the tests pass.
I think the minimal version of sexp_processor to be required in the gemspecs should be increased.

**Comment by zenspider** [comment]
This is what I see when running against my local SP 4.4.4:
```
  5) Failure:
TestRuby2Ruby2#test_block_mystery_block [(eval):8]:
--- expected
+++ actual
@@ -1,4 +1,5 @@
-"a(b) do
+# encoding: US-ASCII
+"a(b) do ||
   if b then
     true
   else
```

not exactly what you're seeing, but close enough... The change in question was 4.6.0:

  * Added and normalized tests to deal with canonicalized block args from ruby_parser.

which is, essentially, a data change to shared tests. One could argue that it is an API change, but it's probably not worth having that argument. That said, except in very specific (and sometimes odd) conditions, those two blocks of code are the semantically equivalent. 

Is this causing problems for you?

**Comment by zenspider** [comment]
anything?

**Comment by boutil** [comment]
Sorry for the delay. I don't see any problem with the library itself.
Just running the tests with an older version of sexp_processor gives
failures, which can appear as a bit worrying.

**Comment by zenspider** [comment]
kk. setting the dep up to 4.6. thanks!
