### ISSUE TITLE
When will ruby2ruby 2.3.3 be released?

### ISSUE THREAD

**Issue by koic** [seattlerb/ruby2ruby#47]
Thanks for the maintenance.

The following warning will occur when using Ruby 2.4.

```console
/Users/koic/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby2ruby-
2.3.2/lib/ruby2ruby.rb:443: warning: constant ::Fixnum is deprecated
```

A commit to suppress this warning was already on the master branch.

520e9dfbcf93f9569e3c1351a9ea88fb2284cdc8

I'd like to use it with warning suppressed.

Thank you.

**Comment by zenspider** [comment]
Soon. I have a whole slew of releases to do soon.

**Comment by koic** [comment]
I get the point. I appreciate your activity.

**Comment by zenspider** [comment]
UGH. This is now released along with a bunch of related gems. Finally. Sorry that took so much longer than expected.

**Comment by koic** [comment]
That's alright. Thank you for releasing :tada:
