### ISSUE TITLE
Add bitwise operators to Ruby2Ruby::BINARY

### ISSUE THREAD

**Issue by david942j** [seattlerb/ruby2ruby#49]
Hi, thanks for this great work!

These bitwise operators should in the list: `^`, `|`,`&`

https://github.com/seattlerb/ruby2ruby/blob/7d23a2c429faf16cb3ad0d33329c6544a6db3129/lib/ruby2ruby.rb#L40

**Comment by zenspider** [comment]
Good catch. Thanks!
